name: data_loader
description: Load Data from server
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.3 <3.0.0'


dependencies:
  path: ^1.8.0
  alfred: ^0.1.4+5
  postgres: ^2.4.1+2
  ftpconnect: ^1.0.1
  xpath_selector: ^2.1.0
  blueprint: ^0.0.3
  retry: ^3.1.0


dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  all_lint_rules_community:
    git: https://github.com/gaetschwartz/all_lint_rules  
